version: "3.8"

services:
  casdoor_auth:
    image: casbin/casdoor-all-in-one
    container_name: casdoor_auth
    ports:
      - "8000:8000"
    networks:
      - casdoor_auth_net

  nginx_auth:
    image: nginx:latest
    container_name: nginx_auth
    ports:
      - "80:80"
      - "8445:8445"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./keys:/etc/nginx/certs
    depends_on:
      - casdoor_auth
    networks:
      - casdoor_auth_net

networks:
  casdoor_auth_net:
    driver: bridge
